apiVersion: v1
kind: Service
metadata:
  name: pos-puc-tcc-front
spec:
  type: NodePort
  selector:
     app: pos-puc-tcc-front   
  ports:
    type: LoadBalancer
    - port: 8080
      targetPort: 80