
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-puc-tcc-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pos.puc.tcc.front
    spec:
      containers:
      - name: pos-puc-tcc-front
        image: andrecanuto/pos.puc.tcc.front:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:
        app: pos.puc.tcc.front        