apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-puc-tcc-front
spec:
  replicas: 1
  selector:
    matchLabels:
        app: pos.puc.tcc.front 
  template:
    metadata:
      labels:
        app: pos.puc.tcc.front
    spec:
      containers:
      - name: app-front
        image: andrecanuto/pos.puc.tcc.front:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: pos-puc-tcc-front
spec:
  #type: NodePort
  type: LoadBalancer
  selector:
     app: pos-puc-tcc-front   
  ports:    
    - port: 8080
      targetPort: 8080
      #nodePort: 31600